- name: Group hosts by whether TLS is enabled
  hosts: pvc_hosts
  gather_facts: no
  tasks:
    - import_tasks: tasks/group_hosts_by_tls.yml

- name: Configure Cloudera Manager agents
  hosts: pvc_hosts
  become: yes
  any_errors_fatal: true
  roles:
    - role: cloudera_manager/agent_config_pvc
      when: pvc_type == "ECS"

- name: Gather facts
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Get manager details (ip)
      delegate_to: "{{ groups.cloudera_manager | first }}"
      run_once: true
      ansible.builtin.set_fact:
        manager_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Get manager details (fqdn)
      delegate_to: "{{ groups.cloudera_manager | first }}"
      run_once: true
      ansible.builtin.set_fact:
        manager_fqdn: "{{ hostvars[inventory_hostname]['ansible_fqdn'] }}"
      when: pvc_type == "ECS"

    - name: Get nameserver IP
      delegate_to: localhost
      run_once: true
      ansible.builtin.command:
        cmd: "awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf"
      register: cmd_result
      changed_when: false

    - name: Set nameserver ip fact
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_fact:
        nameserver_ip: "{{ cmd_result.stdout }}"

    - name: DEBUG | Nameserver ip
      delegate_to: localhost
      run_once: true
      debug:
        var: nameserver_ip

- name: Create a dns and dns-entry for ECS on all PvC servers
  hosts: pvc_hosts
  become: yes
  roles:
    - role: prereqs/pvc_ecs_dns
      when: pvc_type == "ECS"
  tags:
    - os
    - network

- name: Apply specific pre-requisites for ECS
  hosts: pvc_hosts
  become: yes
  roles:
    - role: prereqs/pvc_ecs
      when: pvc_type == "ECS"
  tags:
    - os

- name: Enable a PvC-ECS cluster
  hosts: pvc_hosts
  gather_facts: no
  tasks:
    - ansible.builtin.include_role:
        name: deployment/create_pvc
        tasks_from: uninstall.yml
      when: pvc_type == "ECS"
  tags:
    - pvc

- name: Reboot ECS Hosts
  hosts: pvc_hosts
  gather_facts: no
  tasks:
    - name: Reboot the system if necessary
      ansible.builtin.reboot:

    - name: Ensure firewall is off
      ansible.builtin.systemd:
        name: firewalld
        state: stopped

    - name: Ensure firewall is off
      ansible.builtin.systemd:
        name: dnsmasq
        state: started

- name: Enable a PvC-ECS cluster
  hosts: cloudera_manager
  gather_facts: no
  tasks:
    - ansible.builtin.include_role:
        name: deployment/create_pvc
        tasks_from: install.yml
      when: pvc_type == "ECS"
  tags:
    - pvc
