- name: Group hosts by whether TLS is enabled
  hosts: pvc_hosts
  gather_facts: no
  tasks:
    - import_tasks: tasks/group_hosts_by_tls.yml

- name: Enable a PvC-ECS cluster
  hosts: cloudera_manager
  gather_facts: no
  roles:
    - role: deployment/create_pvc
      when: pvc_type == "ECS"
  tags:
    - pvc
