address=/{{ pvc_app_domain.split('.')[-4:] | join('.') }}/{{ pvc_ecs_server_host_ip.stdout }}
address=/{{ pvc_app_domain }}/{{ pvc_ecs_server_host_ip.stdout }}
address=/apps.{{ pvc_app_domain }}/{{ pvc_ecs_server_host_ip.stdout }}
address=/apps.{{ pvc_app_domain.split('.')[-4:] | join('.') }}/{{ pvc_ecs_server_host_ip.stdout }}
address=/{{ manager_fqdn }}/{{ manager_ip }}

server={{ nameserver_ip }}      # your internal DNS
server=8.8.8.8         # fallback public DNS

